alias rt='rails test'
alias rtp='rails test test/policies'
alias rti='rails test:integration'
alias rtc='rails test:controllers'
alias rts='rails test:system'
alias rtf='annotate && brakeman -q && standardrb && rails test:system test'
alias rtm='annotate && brakeman -q && standardrb && rails test'
